### ISSUE TITLE
Do not print out the progress bar if stdout is redirected

### ISSUE THREAD

**Issue by kasimon** [xorpaul/g10k#101]
If stdout is redirected to anything but a terminal the interactive progress bar should not be printed as it creates ugly log files

<pre>
Resolving Git modules (0/57)   --- [--------------------------------------------------------------------]   0%
ESC[0AESC[2K^MResolving Git modules (0/57)   --- [--------------------------------------------------------------------]   0%
ESC[0AESC[2K^MResolving Git modules (0/57)   --- [--------------------------------------------------------------------]   0%
ESC[0AESC[2K^MResolving Git modules (0/57)   --- [--------------------------------------------------------------------]   0%
ESC[0AESC[2K^MResolving Git modules (0/57)   --- [--------------------------------------------------------------------]   0%
...
</pre>

This should be quite simple to detect: https://rosettacode.org/wiki/Check_output_device_is_a_terminal#Go

**Comment by xorpaul** [comment]
Sure, I can add that. Any reason you're not using `-info` when redirecting to log files?

That's what I'm doing internally at the moment.

**Comment by kasimon** [comment]
Yes, using `-info` works. But then you still have to remember to use that option if you happen to redirect the output. It just would be quite nice if g10k was smart about this by itself. 

Btw, thanks a bunch for g10k. It's really great :)

**Comment by xorpaul** [comment]
Fixed with https://github.com/xorpaul/g10k/releases/tag/v0.4.9 
https://github.com/xorpaul/g10k/blob/master/puppetfile.go#L203

**Comment by kasimon** [comment]
Thanks a lot!
