### ISSUE TITLE
400 Bad Request when querying Puppet Forge

### ISSUE THREAD

**Issue by alexharv074** [xorpaul/g10k#104]
I am trying to install modules using g10k, and getting a 400 Bad Request response for all of them.

My Puppetfile:

``` ruby
forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs/stdlib'
mod 'puppetlabs/haproxy'
mod 'puppetlabs/ntp'
mod 'puppetlabs/lvm'
mod 'puppetlabs/firewall'
mod 'alexharvey/firewall_multi'
mod 'alexharvey/disable_transparent_hugepage'

# Workaround for Issue #167.
#
mod 'pcfens/filebeat',
  :git => 'https://github.com/alexharv074/puppet-filebeat.git',
  :ref => 'Issue_167'

# Until my PRs to fix Issues #947 and #949 are merged.
#
mod 'elastic/elasticsearch',
  :git => 'https://github.com/alexharv074/puppet-elasticsearch.git',
  :ref => 'alex_master'

mod 'elastic/logstash'
mod 'arioch/redis'
mod 'elastic/kibana'
mod 'puppet/nginx'
mod 'camptocamp/archive'
mod 'thias/sysctl'

# Until next version is released.
#
mod 'basti1302/wait_for',
  :git => 'https://github.com/heini/puppet-wait-for'
```

The response is variously something like:

``` text
downloadForgeModule(): Unexpected response code while GETing https://forgeapi.puppetlabs.com/v3/files/basti1302-wait_for-git.tar.gz 400 Bad Request
```

This Puppetfile works fine when using Librarian-puppet, and seems fine based on the docs at this project.

**Comment by xorpaul** [comment]
You have to specify git modules like this:

```
mod 'apache',
  :git => 'https://github.com/puppetlabs/puppetlabs-apache.git'
```
Note the missing `<AUTHOR>/` in the module name.

This is a documented breaking change:
https://github.com/xorpaul/g10k#changes-breaking-complete-r10k-compatibility

I'm leaving this issue open for now though, because I'll have another look into supporting this module notation

**Comment by xorpaul** [comment]
I've got something working, but it's pretty hacky and I don't know if I want to merge that:

https://github.com/xorpaul/g10k/commit/4acd973f0cc6d22e31626bbbffb441f610e3bc52#diff-b4bda758a2aef091432646c354b4dc59R233

You can try it here:
[g10k-linux-amd64-issue104.zip](https://github.com/xorpaul/g10k/files/2149472/g10k-linux-amd64-issue104.zip)

**Comment by alexharv074** [comment]
@xorpaul Ah, ok. I would need the Mac version to try that out for you.

In my project, I was hoping to do something that's compatible with r10k/g10k/librarian as I was concerned that Puppet users might feel that a dependency on a Go project is too radical! I take it you mean by the above that you have decided to also support the `mode author/module` syntax too going forward?

If you send me a Mac version of the above I'll definitely try it out.

**Comment by xorpaul** [comment]
Sure here is the Mac version: 
[g10k-darwin-amd64-issue104.zip](https://github.com/xorpaul/g10k/files/2149915/g10k-darwin-amd64-issue104.zip)

I'm still undecided if I want to support my own dirty hack to support the `mod author/module` for Git modules :wink:

**Comment by alexharv074** [comment]
I guess there are dirty hacks, and then there is not implementing the API. ;-)

**Comment by alexharv074** [comment]
Anyhow I am afraid that hasn't fixed the issue.

**Comment by alexharv074** [comment]
```
2018/06/30 01:36:17 DEBUG downloadForgeModule(): GETing https://forgeapi.puppetlabs.com/v3/files/basti1302-wait_for-git.tar.gz
2018/06/30 01:36:18 GETing https://forgeapi.puppetlabs.com/v3/files/basti1302-wait_for-git.tar.gz took 1.15152s
downloadForgeModule(): Unexpected response code while GETing https://forgeapi.puppetlabs.com/v3/files/basti1302-wait_for-git.tar.gz 400 Bad Request
```

**Comment by xorpaul** [comment]
Sorry, I've switched my local git branch back to master before building the Mac version.

Try this: 
[g10k-darwin-amd64-issue104.zip](https://github.com/xorpaul/g10k/files/2150008/g10k-darwin-amd64-issue104.zip)

**Comment by xorpaul** [comment]
You should get something like this with `-debug`:

```./g10k -puppetfile -debug
Fr 29. Jun 17:42:52 CEST 2018
2018/06/29 17:42:52 DEBUG main(): Trying to use as Puppetfile: ./Puppetfile
2018/06/29 17:42:52 DEBUG checkDirAndCreate(): Using as cachedir default value: /tmp/g10k/
2018/06/29 17:42:52 DEBUG readPuppetfile(): Trying to parse: ./Puppetfile
2018/06/29 17:42:52 DEBUG preparePuppetfile(): adding line:mod 'elastic/elasticsearch',
2018/06/29 17:42:52 DEBUG preparePuppetfile(): adding line::git => 'https://github.com/alexharv074/puppet-elasticsearch.git',
2018/06/29 17:42:52 DEBUG preparePuppetfile(): adding line::ref => 'alex_master'
2018/06/29 17:42:52 DEBUG readPuppetfile(): setting forge module elastic/elasticsearch to version git
2018/06/29 17:42:52 DEBUG readPuppetfile(): found forge attribute ---> :git with value ---> https://github.com/alexharv074/puppet-elasticsearch.git
2018/06/29 17:42:52 DEBUG readPuppetfile(): Found git module in Forge notation: elastic/elasticsearch with git url: https://github.com/alexharv074/puppet-elasticsearch.git
2018/06/29 17:42:52 DEBUG readPuppetfile(): Using replaced Puppetfile content, probably because a Git module was found in Forge notation
2018/06/29 17:42:52 DEBUG readPuppetfile(): Setting moduledir for Puppetfile mod 'elasticsearch',:git => 'https://github.com/alexharv074/puppet-elasticsearch.git',:ref => 'alex_master'
 to modules
```

**Comment by alexharv074** [comment]
Great that works!

**Comment by xorpaul** [comment]
I merged it to master.
I hope I don't regret it :smirk:
