### ISSUE TITLE
PuppetForge Module

### ISSUE THREAD

**Issue by Conzar** [xorpaul/g10k#109]
Greetings,
  I am the lead developer of a g10k puppet module.

* [Forge](https://forge.puppet.com/landcareresearch/g10k)
* [Source](https://bitbucket.org/landcareresearch/puppet-g10k)

Please let me know if you would like any additional documentation on the readme or anything else.

Thank you for this project.  g10k is much faster than r10k and speeds up our workflow.

**Comment by xorpaul** [comment]
Cool stuff! Thank you.

I'll add a link to the README.

I've looked over the module and already have a few suggestions ;)
I'll open up a issue in your Bitbucket project for that.

**Comment by xorpaul** [comment]
Done and done. 
- https://bitbucket.org/landcareresearch/puppet-g10k/issues/1/support-multiple-g10k-config-files
- https://github.com/xorpaul/g10k#installation-of-g10k-via-puppet-module
