### ISSUE TITLE
Exclude directory from purge

### ISSUE THREAD

**Issue by walkamongus** [xorpaul/g10k#115]
Hello,

Is there currently a way to exclude a directory from being purged from an environment? This becomes important when Puppet resource types are generated to enable environment isolation. Generating types creates a `.resource_types` directory to be created in each environment directory and if this directory is purged on the next code update, when it is re-created it causes the agents to re-download all the plugins again, which becomes expensive really quickly if there are semi-frequent updates to an environment.

**Comment by xorpaul** [comment]
You could've only excluded folders inside the `moduledir` ("modules" by default) by using the `local` attribute:

```
mod 'local_module', :local => true
```

Anyway I've added `.resource_types` as a directory to be excluded from the g10k purge in every case.
Check out https://github.com/xorpaul/g10k/releases/tag/v0.5.5

**Comment by walkamongus** [comment]
@xorpaul I appreciate it! Thanks so much!
