### ISSUE TITLE
correct_and_warn always issues warning even if environment name is not changed

### ISSUE THREAD

**Issue by cbowman0** [xorpaul/g10k#120]
When setting `invalid_branches` to `correct_and_warn`, every environment is printed with a warning that the name was change, even if none of the names were changed.

The documentation is not clear that this is expected.

I suspect the appropriate situation to check if `oldBranch != renamedBranch` before warnF()/debugF().

**Comment by xorpaul** [comment]
You're right, there's no reason to output every environment name, when it's not modified:  https://github.com/xorpaul/g10k/commit/e192e6429fb8b27c07c2bc00a304a78a66f8623e
Check out:
https://github.com/xorpaul/g10k/releases/tag/v0.6.0
