### ISSUE TITLE
untar sometimes fail on removing unexisiting file

### ISSUE THREAD

**Issue by maxenced** [xorpaul/g10k#145]
On new env deployment, g10k fails with errors like : 

```
"unTar(): error while removing existing file /etc/puppetlabs/code/environments/myenv/modules/logstash_legacy/spec/fixtures/modules/logstash/manifests to be replaced with symlink pointing to ../../../../manifests Error: remove /etc/puppetlabs/code/environments/myenv/modules/logstash_legacy/spec/fixtures/modules/logstash/manifests: no such file or directory"
```

It fails on many modules which use symlink, all have git reference in Puppetfile. 

I suspect this is related to https://github.com/xorpaul/g10k/blob/244e8a8ed18bb775019973ec9f424bfd0189d559/modules.go#L85

**Comment by xorpaul** [comment]
I've already released a hotfix for this. Did you check out v0.7.2?

https://github.com/xorpaul/g10k/releases/tag/v0.7.2

**Comment by maxenced** [comment]
Indeed, sorry, you're too fast for me :)

**Comment by xorpaul** [comment]
Hehe, no problem. :smirk: 

It's really my fault for releasing v0.7.1 with the symlink bug in the first place.
