### ISSUE TITLE
unTar(): error while creating symlink ... file exists

### ISSUE THREAD

**Issue by maxadamo** [xorpaul/g10k#149]
hello @xorpaul 

it was a while since I didn't not update `g10k`, then I jumped from version 0.6.1 to verions 0.8.1 (and then 0.8.2, without solving the issue) and g10k started throwing the following error:  
```
unTar(): error while creating symlink modules/hieradata/hostgroups/kube-control.yaml pointing to kube-master.yaml Error: symlink kube-master.yaml modules/hieradata/hostgroups/kube-control.yaml: file exists
```

It throws the error, always on this same file: `kube-control.yaml`, and on both puppet servers (I have two puppet servers). 
To clean the error I had to delete all the file and run g10k again. 
To solve the problem I had to roll-back to a working version (for me it's 0.6.1)

Now, *I am trying a git diff between tags, to ensure that you're not doing anything around the word "control"*

**Comment by xorpaul** [comment]
Is `kube-control.yaml` a simple symlink inside a Puppetfile managed module, yes?

**Comment by maxadamo** [comment]
yes (I have 70 symlinks in hiera).

**Comment by maxadamo** [comment]
I can't imagine what it can be wrong with the name, but perhaps you can create a file called `kube-master.yaml`, and a symlink called `kube-control.yaml` pointing to `kube-master.yaml`.
