### ISSUE TITLE
allow disabling module deprecation check or cache results

### ISSUE THREAD

**Issue by juliantaylor** [xorpaul/g10k#152]
g10k runs significantly slower since we updated to 0.8. The reason is the forge query done also for already synced module to check for deprecation in https://github.com/xorpaul/g10k/blob/master/forge.go#L115
In our environments we more than 50 modules and the forge mirror we use is relatively slow.

Would it be possible to either disable it completely or cache the deprecation result for already synced modules so one does not have to query all modules on each update?

I could probably provide a patch.

**Comment by juliantaylor** [comment]
posted https://github.com/xorpaul/g10k/pull/153 which prints deprecation warnings also if the module is cached and respects the module TTL to refresh the cache.

**Comment by xorpaul** [comment]
Thanks, I really thought I already respected the Forge cache TTL setting when checking for a deprecation notice.

Looks like I only thought about it, but did not implement it.

Regarding the failing tests, I also need to fix some other things first before merging your patch.
