### ISSUE TITLE
Travis-ci: build is failing on AMD64

### ISSUE THREAD

**Issue by sanjaymsh** [xorpaul/g10k#172]
Hi,

I am trying to build it on travis-ci, but its failing for amd64 itself with below error:
"vendor/gopkg.in/yaml.v2/yamlprivateh.go:115:6: don't use underscores in Go names; func is_breakz should be isBreakz
vendor/gopkg.in/yaml.v2/yamlprivateh.go:128:6: don't use underscores in Go names; func is_spacez should be isSpacez
vendor/gopkg.in/yaml.v2/yamlprivateh.go:142:6: don't use underscores in Go names; func is_blankz should be isBlankz
Makefile:13: recipe for target 'lint' failed
make: *** [lint] Error 1
The command "make" exited with 2.
Done. Your build exited with 1." 

Here is the full log: https://travis-ci.com/github/sanjaymsh/g10k/builds/188917938

Please have a look on this.
Thanks !!

**Comment by xorpaul** [comment]
The linter from TravisCI complains about external libraries in the `vendor` directory, but if I just remove that folder, then TravisCI can't build g10k anymore...

**Comment by xorpaul** [comment]
Tests and build is working again thanks to #176 from @bkuebler
