### ISSUE TITLE
debug switch not working in puppetfile mode

### ISSUE THREAD

**Issue by TheMeier** [xorpaul/g10k#19]
the debug switch seems not to be working in puppetfile mode

`10:39 $ ./g10k  -debug -config  ./r10k.yaml  
2016/08/11 10:39:24 DEBUG Using as config file: ./r10k.yaml
2016/08/11 10:39:24 DEBUG Using as cachedir: ./tmp/g10k/
2016/08/11 10:39:24 DEBUG Using as cachedir/forge: ./tmp/g10k/forge/
2016/08/11 10:39:24 DEBUG Using as cachedir/modules: ./tmp/g10k/modules/
2016/08/11 10:39:24 DEBUG Using as cachedir/environments: ./tmp/g10k/environments/
Synced ./r10k.yaml with 0 git repositories and 0 Forge modules in 0.0s with git (0.0s sync, I/O 0.0s) and Forge (0.0s query+download, I/O 0.0s)
`

`10:39 $ ./g10k -puppetfile install  -debug -config  ./r10k.yaml  
Synced ./Puppetfile with 14 git repositories and 35 Forge modules in 3.1s with git (23.5s sync, I/O 0.8s) and Forge (0.0s query+download, I/O 1.9s)
`

**Comment by xorpaul** [comment]
I've added an error message if you try to use the `-config` and the `-puppetfile` parameter, as that should have never worked.

You either want the Puppetfile mode or use a g10k/r10k config.

```
./g10k -puppetfile -debug -config ./r10k.yaml                                                                                                            
2016/08/11 17:17:38 Error: -puppetfile parameter is not allowed with -config parameter!
```

The reason that you don't see any debug messages is that you added an invalid argument `install` probably from the r10k command, which should not be recognized as a valid g10k parameter in the first place, but the golang `flag` module doesn't seem to mind.

So make sure that you use the parameter correctly:
```
./g10k -puppetfile -debug
```

It would be better if g10k would detect this, but I did not see an option for this in the `flag` module.
