### ISSUE TITLE
Fallback-Option for linked=>true

### ISSUE THREAD

**Issue by Slm0n87** [xorpaul/g10k#31]
The 'link => true' feature from bkuebler in #6  for syncing 'linked' environments is very cool and useful if you are working in predefined environments (dev->prelive->live).  
But with this feature you are currently forced to create 'own' branches for every linked module to have a working puppet-environment (working g10k-sync).  

So it is not easy to create own branches anymore for testing.  

For that a kind of 'link-fallback' would be great.  
So that g10k still tries to sync a branch with the same name as the environments branch, but if this does not exist using the fallback-branch.  
That fallback-branch could for example be set 'hard-coded' to the default-branch of the git - or could be configured by an additional 'link-fallback'-attribute in Puppetfile.  

Thx and Greets
Simon

**Comment by xorpaul** [comment]
Feature is already there:
```
mod 'stdlib',
    :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
    :link => true,
    :fallback => '4.889.x|foobar|master'
```
Checkout the last additional feature https://github.com/xorpaul/g10k/blob/master/README.md#additional-puppetfile-features
