### ISSUE TITLE
Introduce vendoring

### ISSUE THREAD

**Issue by ntnn** [xorpaul/g10k#32]
I'd like to see vendoring.

This would help with automated builds as well as initial setups. Go 1.8 will likely also change the default behaviour with requiring to be inside the gopath to build vendored projects as well, which would remove the hacky-wacky temporary gopaths as well.

**Comment by xorpaul** [comment]
added vendor/ with the help of https://github.com/kardianos/govendor

Have a look if it's what you were looking for.

**Comment by ntnn** [comment]
Yes, thanks a bunch mate.
