### ISSUE TITLE
Use `-branch` in Puppetfile mode

### ISSUE THREAD

**Issue by ntnn** [xorpaul/g10k#33]
In Puppetfile mode g10k refurses to synchronize modules with the `:link`
parameter, suggesting to set `g10k_branch` as an environment variable.

Since the flag `-branch` already exists and is documented for
config-file mode I'd suggest to use this flag as well for Puppetfile
mode.

**Comment by xorpaul** [comment]
Fixed with #49

**Comment by ntnn** [comment]
Thanks
