### ISSUE TITLE
Allow overriding moduledir set in puppetfile with `-moduledir $dir` flag

### ISSUE THREAD

**Issue by ntnn** [xorpaul/g10k#34]
This would primarily be handy to use g10k as a fixture tool to place modules in a temporary directory to refer to while testing.

It would be great for both the puppet- and configfile mode.

**Comment by xorpaul** [comment]
Done.
```
-moduledir string
        allows overriding of Puppetfile specific moduledir setting, the folder in which Puppet modules will be extracted
```

Now moduledir can also be set to an absolute path in the Puppetfile or via the new -moduledir parameter.

https://github.com/xorpaul/g10k/releases/tag/v0.2.7

**Comment by ntnn** [comment]
Perfect, thanks a bunch!
