### ISSUE TITLE
:ignore-unreachable alternative :ignore_unreachable

### ISSUE THREAD

**Issue by ntnn** [xorpaul/g10k#35]
Ruby symbols cannot have a hyphen in their name, which causes other tools, which evaluate the Puppetfile as ruby code, to fail.

A viable alternative would be `:ignore_unreachable`, in addition to `:ignore-unreachable`.

**Comment by xorpaul** [comment]
Both notations are supported:

https://github.com/xorpaul/g10k/blob/master/config.go#L112

**Comment by ntnn** [comment]
Thanks a bunch.
