### ISSUE TITLE
limiting concurrent sessions

### ISSUE THREAD

**Issue by maxadamo** [xorpaul/g10k#38]
I was wondering whether it could be convenient to have an option to limit the number of sessions. 
In my case I have around 85 repository, and I see that gitlab is not very happy. Soon I am gonna add a second puppet server and therefore, I'll need to use `flock` to span the trigger once at time . 

I could also considering to go back to Go(-lang), try to add this option and make a pull request.... 

**p.s.**: congrats for the nice job that you have done, which I like very much. 
With r10k I was able to fetch the repositories in almost 5 minutes. Thanks to g10k (also adding ssh control master, and one CPU to Gitlab) I am able to fetch in 8 seconds!!

**Comment by maxadamo** [comment]
it would have been easier to add options if you used docopt (it exists either for Pytthon and for Go).

**Comment by xorpaul** [comment]
Thanks for your kind works, I know g10k still has some rough edges, but we like the performance increase very much :)

We are using a single server in front of all Puppetservers that runs g10k once and then rsync all Puppet environments to the Puppetservers instead of triggering g10k on each Puppetserver.
Otherwise running almost 100 Puppetserver would/should trigger DDOS protection on the Puppetlabs Forge or github.com anyway, besides wasting resources.

I added limitation of the maximum number of goroutines running for Git/Forge resolving.

Try it out.
https://github.com/xorpaul/g10k/releases/tag/v0.2.8b
https://github.com/xorpaul/g10k/commit/db95104de12546e7d5778da12f9f4e9fc569fcf7

**Comment by maxadamo** [comment]
it's impressing! With the older version I was able to fetch in 8 seconds, with this new version I am able to fetch in 2 seconds

**Comment by xorpaul** [comment]
Wow, are you sure that your not just using the cached Git and Forge modules now?
Was it really the overload of your Gitlab server that slowed down your previous g10k runs?
How many workers are you using right now?

**Comment by maxadamo** [comment]
I didn't set the worker limit right now (as I don't have the 2nd puppet server yet), but I played a bit with it and I have seen a strange behavior when I set it to a very low value (a meaningless value, lower than 5).
In this case it throws an error, saying that it cannot connect to my Gitlab server (with the usual error message: please check if you have put you keys... ). 
The other difference, is that now I used the binary compiled by you, while in the previous case, I compiled the binary on a RedHat 6 (which means that I surely used some older version of Go).

**Comment by maxadamo** [comment]
Hi. I have been working on this: 
https://github.com/maxadamo/g10k-webhook  (until I decide to move everything on the public Gitlab). 
It's a drop-in replacement for r10k_gitlab_webhook, enhanced with a lot of steroids.  
it would have been nicer to to it with Go, but it would have taken ages compared to python. 

Honestly, I don't understand if it's good for generic use, of if it fits too much my environment.

**Comment by gdubicki** [comment]
This would be useful for me too.

**Comment by xorpaul** [comment]
I still need to find a bug introduced by https://github.com/xorpaul/g10k/commit/db95104de12546e7d5778da12f9f4e9fc569fcf7 before I can merge it.
For some reason it waits indefinitely for a go routine.

**Comment by xorpaul** [comment]
Found the bug, missing waitgroup https://github.com/xorpaul/g10k/commit/19b953df3a2cb474a0f768d9215489d75a0a8b03#diff-b112433c20987b983fa33aa1eac9482dR58

Relase: https://github.com/xorpaul/g10k/releases/tag/v0.3.7

**Comment by xorpaul** [comment]
Seems like the `-maxworker` parameter has never worked.

It should be fixed now with [v0.7.1](https://github.com/xorpaul/g10k/releases/tag/v0.7.1)

https://github.com/xorpaul/g10k/pull/141
