### ISSUE TITLE
error with symlinks

### ISSUE THREAD

**Issue by maxadamo** [xorpaul/g10k#51]
Hey,
I've just installed the newer version, and I have seen this error with symlinks:
```
2017/03/22 13:25:39 unTar(): Unable to untar type: 2 in file hostgroups/host-a.yaml
```
I rolled back to the older g10k and it started working again.

**Comment by xorpaul** [comment]
Should be fixed in https://github.com/xorpaul/g10k/releases/tag/v0.3.1 please verify.

**Comment by maxadamo** [comment]
Yes. you can close the issue.
