### ISSUE TITLE
Problem with specific module version -beta1

### ISSUE THREAD

**Issue by robrankin** [xorpaul/g10k#52]
Specific module:
```
https://forge.puppet.com/mayflower/php
```

Puppetfile
```
mod 'mayflower-php', '4.0.0-beta1'
```

Error
```
2017/03/23 08:28:57 downloadForgeModule(): Unexpected response code while GETing https://forgeapi.puppetlabs.com/v3/files/mayflower-php-4.0.0.tar.gz 404 Not Found
```

g10k seems to be ignoring/stripping the `-beta1` from the version and therefore the package name?

GET'ng the `mayflower-php-4.0.0-beta1.tar.gz` package manually works correctly.

**Comment by xorpaul** [comment]
Should be fixed in https://github.com/xorpaul/g10k/releases/tag/v0.3.2

**Comment by robrankin** [comment]
👍 

Thanks!
