### ISSUE TITLE
g10k unTar() sets 0644 for external facts

### ISSUE THREAD

**Issue by ntnn** [xorpaul/g10k#53]
Expected behaviour: Files with executable bits in git have the executable bit set after synchronization
Actual behaviour: All files have mode of 0644

Error: https://github.com/xorpaul/g10k/blob/master/forge.go#L329

The permission bits will have to be recovered through the file header.

**Comment by xorpaul** [comment]
Thanks, fixed in https://github.com/xorpaul/g10k/releases/tag/v0.3.3
