### ISSUE TITLE
dependencies failing to install 

### ISSUE THREAD

**Issue by alexharv074** [xorpaul/g10k#60]
I am trying to install this but getting the following:

```
Alexs-MacBook-Pro:g10k alexharvey$ export GOPATH=/Users/alexharvey/git/g10k
Alexs-MacBook-Pro:g10k alexharvey$ go get
# cd .; git clone https://gopkg.in/yaml.v2 /Users/alexharvey/git/g10k/src/gopkg.in/yaml.v2
Cloning into '/Users/alexharvey/git/g10k/src/gopkg.in/yaml.v2'...
fatal: unable to access 'https://gopkg.in/yaml.v2/': Unknown SSL protocol error in connection to gopkg.in:-9838
package gopkg.in/yaml.v2: exit status 128
```

I am completely new to Go. Is the issue here that g10k is depending on gopkg.in/yaml.v2 which no longer exists?

**Comment by alexharv074** [comment]
Ok, I found this https://github.com/niemeyer/gopkg/issues/49

**Comment by ntnn** [comment]
The package does exist. 

As the client said, there was an error in the SSL connection. Retry and also give the version of your go binary (`go version`). Generally this is something for the go community in general, e.g. `#go-nuts` on freenode.

**Comment by alexharv074** [comment]
As a Puppet/Ruby user, I don't share your enthusiasm for learning another language, just to speed up r10k. :)  Good work though; I'm sure this will be awesome, if I ever get it to work.

Anyhow, here's the command output:

```
$ go version
go version go1.6.1 darwin/amd64
```

**Comment by xorpaul** [comment]
Is there a reason you don't just use the compiled releases? 
https://github.com/xorpaul/g10k/releases

**Comment by alexharv074** [comment]
Well the README seemed to imply that I should build it from source, however compiled releases sounds like a much better idea! I will give that a try, thanks again.

**Comment by xorpaul** [comment]
Fair enough :)

I've added a hint in the readme file:

https://github.com/xorpaul/g10k#installation

**Comment by alexharv074** [comment]
Do you have a pre-compiled version for Mac OS X?

```
$ g10k --help
-bash: /usr/local/bin/g10k: cannot execute binary file
```

**Comment by alexharv074** [comment]
My use-case, and I suspect a lot of people will be the same, is to speed up r10k when running the Rspec-puppet tests. So, unlike r10k as used to deploy onto a Puppet Master, it could really be any platform.

**Comment by xorpaul** [comment]
Sure, here you go:

https://github.com/xorpaul/g10k/releases/download/v0.3.6/g10k-darwin-amd64.zip

**Comment by alexharv074** [comment]
Thanks very much for your help! It's working!
