### ISSUE TITLE
Optionally specifying filename to -puppetfile

### ISSUE THREAD

**Issue by jovrum** [xorpaul/g10k#68]
[librarian-puppet](https://github.com/voxpupuli/librarian-puppet) allows the name `Modulefile` with the same syntax as `Puppetfile`, and `g10k` could be used as a drop-in replacement. Also, such an option could be used to specify a `Puppetfile` in a different directory than the working directory.

**Comment by xorpaul** [comment]
Added `-puppetfilelocation` parameter to specify which Puppetfile to use in -puppetfile mode (default "./Puppetfile")

https://github.com/xorpaul/g10k/releases/tag/v0.3.11

**Comment by jovrum** [comment]
Thanks a lot!
