### ISSUE TITLE
Per item install_path is not supported

### ISSUE THREAD

**Issue by mchouque** [xorpaul/g10k#69]
Hello,

Looking at the code, it appears "install_path" isn't supported. It is described as the following by puppetlabs:
https://github.com/puppetlabs/r10k/blob/master/doc/puppetfile.mkd

Is it something you plan to support?

Cheers,
Mathieu

**Per-Item Install Path**

Git and SVN content types support installing into an alternate path without changing the value of moduledir by specifying an 'install_path' option:

```# This will install the 'apache' module into 'external/apache'.
mod 'apache',
  :git => 'git@github.com:puppetlabs/puppetlabs-apache.git',
  :install_path => 'external'
```
The given 'install_path' can be an absolute path or a path relative to the base of the environment. Note that r10k will exit with an error if you attempt to set the 'path' option to a directory outside of the environment.

**Comment by xorpaul** [comment]
Looks easy enough. I'll look into it.

**Comment by xorpaul** [comment]
Fixed with https://github.com/xorpaul/g10k/releases/tag/v0.3.12

**Comment by mchouque** [comment]
That was quick, thank you very much!
