### ISSUE TITLE
Problems with puppet runs during g10kr

### ISSUE THREAD

**Issue by rogerlz** [xorpaul/g10k#72]
Hi, 

I have ~50 environments/branches in my production repository (yeah, I know) and I'm using g10k to deploy the Puppetfiles which is 10x faster than r10k. Thanks for that. 

Due to the number of environments and IO of my EC2 puppet master, g10k is taking ~20s to run. Having ~400 puppet agents behind the master, almost always there is puppet run during the g10k run and, of course, an incomplete repository. 

Provisioning more IO to the EC2 seems to reduce the issue since the g10k will be able to finish even faster, but the cost math becomes a problem, especially with 15 puppet masters. 

I thought in a feature to symlink/move the environment dir after the g10k successful run.

Any better solution?

Thanks

**Comment by xorpaul** [comment]
I'm using a sync server that is there only for g10k runs.

If the g10k run was successful the resulting fully populated environments are transfered to the Puppetservers, if not no files are transfered and the Puppetservers run with the last known good environments.

You could change your g10k target directory to a different directory outside of your Puppetserver environment directory and copy or symlink that directory in case the g10k run was successful.

Currently there is no way to issue a command after an successfull g10k runs withing g10k, so you would need to do that yourself.

Something like:

```
$ g10k -config foobar.yaml -info && rsync -av --delete <G10KBASEDIR> /etc/puppetlabs/code/environments
```

**Comment by rogerlz** [comment]
Yeah, it's the same thought that I had. I would only change the --delete rsync arg to --delete-after. 

Thanks for the reply.
