### ISSUE TITLE
:default_branch and ':branch => :control_branch' are not supported

### ISSUE THREAD

**Issue by mchouque** [xorpaul/g10k#73]
Hello,

It's me again! :-)

Looking at the code it appears g10k doesn't support a default_branch keyword nor using a fallback to the control_branch as per:
[https://docs.puppet.com/pe/latest/cmgmt_puppetfile.html#set-a-default-branch-for-content-deployment]()

>Set a default branch for content deployment
>You can set a default_branch option, which specifies what branch to deploy content from if the given ref, tag, commit, or branch option cannot be resolved and deployed. This is mostly useful when you set branch to the :control_branch value.

>If the desired content cannot be resolved and no default branch is given, or if the default branch cannot be resolved, an error is logged and the content is not deployed or updated.

As such, they give the following example (which is pretty much how I use it):

```# Track control branch and fall-back to master if no matching branch.
mod 'hieradata',
  :git    => 'git@git.example.com:organization/hieradata.git',
  :branch => :control_branch,
  :default_branch => 'master'
```

Let me know if this is something you plan to support.

Cheers,
Mathieu

**Comment by xorpaul** [comment]
You looked through the code, but not through the README? :stuck_out_tongue_winking_eye: 

That feature is already in place, although under different names:

```
mod 'hieradata',
  :git    => 'git@git.example.com:organization/hieradata.git',
  :link => 'true',
  :fallback => 'master'
```

Because I implemented those features before r10k had them.

Maybe I'll try to support the r10k attribute names in the future.

**Comment by xorpaul** [comment]
Added r10k settings `:default_branch` and `:control_branch` with `v0.3.14` https://github.com/xorpaul/g10k/releases/tag/v0.3.14

**Comment by xorpaul** [comment]
Added hints to the README
