### ISSUE TITLE
Please update documentation about different behavior between r10k and g10k

### ISSUE THREAD

**Issue by riton** [xorpaul/g10k#78]
First of all, thanks !
I was planning to implement _something like r10k_ in _GoLang_ and then I found your project. Big kudos to you !

Then I've tried to use `g10k` on the `Puppetfile` we're using and I hit bug #2 .
I had to dig into the code to really understand why it was _mis-interpreting_ (differently as _r10k_) our git based modules as forge modules. And then I found the bug.

Can you please update the documentation and mention that this behavior is different than _r10k_ one ? This could save next person some time :-)

Note : maybe that #2 can be closed if you do not plan to support it at all ?

Thanks !

**Comment by blackknight36** [comment]
I second this.  g10k claims to be a drop-in replacement for r10k but in truth it requires changes to your puppetfile to work properly.

**Comment by xorpaul** [comment]
Removed any mention of drop-in replacement from readme
