### ISSUE TITLE
grab version number from tag name?

### ISSUE THREAD

**Issue by maxadamo** [xorpaul/g10k#83]
Hi. 
I see that some time you forget to update the version number.  For instance, now I have built 0.4.4, but: 
> maxadamo@lenovo:~/go/src/g10k ((v0.4.4))$ ./g10k -version
> g10k version 0.4.3 Build time:  UTC

I see actually two possible solutions:
1) put a sticket on you monitor: `remember to update the version number :)`. Then you need a 2nd reminder: `remember to check the sticker on my display :)`
2) grab it from the tag name

**Comment by xorpaul** [comment]
Argh... 🙄 

I think creating a small release creating bash script which automatically adjusts the version number inside the g10k.go before building, packaging and uploading the binary files to github should fix that.

I promise I'll create and use it next time. Until that I'm leaving this open as a reminder

**Comment by maxadamo** [comment]
forgive me for the errors and bad syntax but 
> tag_out, err := exec.Command("git", "describe", "--tags").Output()
> fmt.Println("g10k version %s Build time:, buildtime, "UTC", tag_out)

**Comment by maxadamo** [comment]
I made a pull request. It seems to be working, but I recommend to double, and triple check it, as I am still bad with Go-Lan :)

**Comment by xorpaul** [comment]
I'm using a simple bash script now to make sure the version number gets updated: https://github.com/xorpaul/g10k/blob/master/build_release.sh
