### ISSUE TITLE
g10k fails with 404 when grabbing latest puppetlabs/git from Forge

### ISSUE THREAD

**Issue by jovrum** [xorpaul/g10k#88]
```
jovrum-desktop~/testcase % cat Puppetfile 
mod 'puppetlabs/git', :latest
jovrum-desktop~/testcase % g10k -verbose -puppetfile
2017/12/21 14:50:28 Querying Forge API https://forgeapi.puppetlabs.com/v3/modules?query=git&owner=puppetlabs&show_deleted=false&limit=1 took 1.12915s
2017/12/21 14:50:29 GETing https://forgeapi.puppetlabs.com/v3/files/puppetlabs-git-2.2.0.tar.gz took 0.84638s
downloadForgeModule(): Unexpected response code while GETing https://forgeapi.puppetlabs.com/v3/files/puppetlabs-git-2.2.0.tar.gz 404 Not Found
```

For the given query, Forge seems to return information for `puppetlabs/vcsrepo` instead of `puppetlabs/git`, so it thinks the latest version of `git` is 2.2.0, but that's actually the latest version of `vcsrepo`. Maybe it's possible to use a more specific/exact query?

**Comment by maxadamo** [comment]
@jovrum it seems yo be your typo. 
there is mod 'puppetlabs-git', '0.5.0' and mod 'puppetlabs-vcsrepo', '2.2.0'
But not puppetlabs-git 2.2.0

**Comment by jovrum** [comment]
@maxadamo - I'm using `:latest`, not specifying version anywhere. You can see the problem by accessing https://forgeapi.puppetlabs.com/v3/modules?query=git&owner=puppetlabs&show_deleted=false&limit=1 directly.

**Comment by xorpaul** [comment]
Very weird. It seems that the Puppetlabs Forge API does find a module that has to do with the keyword `git` instead finding the module named `git`.

Maybe the `name` parameter doesn't work as I thought it would.

**Comment by xorpaul** [comment]
Reverted back to /modules/ so the query URL is now https://forgeapi.puppetlabs.com/v3/modules/puppetlabs-git which returns the expected module and the correct latest version.

**Comment by jovrum** [comment]
@xorpaul, thanks!
