### ISSUE TITLE
feature: only clone if branch/tag/commit exists

### ISSUE THREAD

**Issue by Z3po** [xorpaul/g10k#9]
It would be cool additional to feature https://github.com/xorpaul/g10k/issues/6 bringing linking support to puppet environments to have the possibility to specify in the puppetfile to ignore checkout errors.
That could mean something like 

    mod 'site',
      :git => 'git@puppet-repo.server.lan:pomailcore/site.git',
      :branch => "mybranch",
      :ignore-unreachable => 'True'

Or combined with the new feature referenced:

    mod 'site',
      :git => 'git@puppet-repo.server.lan:pomailcore/site.git',
      :link => 'True',
      :ignore-unreachable => 'True'

That causes all you puppetfiles in all environments to look the very same.
Now if you're working on a module and want to test these changes e.g. in your _"QA"_ stage, you could branch the specific git repository to the branch _"QA"_ and after triggering g10k it's available within the environment, without the need to manually specify any new versions through your Puppetfile.

Now it's not necessary anymore to keep all branches in all GIT Repositories _"available"_ but just create them, once you need them.

**Comment by xorpaul** [comment]
added ignore-unreachable parameter for GIT module with #14
