### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by rogerlz** [xorpaul/g10k#90]
Hi, 

r10k supports proxy in the r10k.yaml (https://github.com/puppetlabs/r10k/blob/master/r10k.yaml.example)

It would be good to have that feature available for g10k. Any thoughts before I start coding a patch?

Thanks

**Comment by xorpaul** [comment]
I really thought I mentioned proxy support in the readme or in the `--help` output.

Like `curl`, `wget` or `git` you can set the environment variables `http_proxy` and/or `https_proxy` for `g10k`

https://github.com/xorpaul/g10k/blob/394c5f6cd520eca7698bf6bdeefdc5a3a8c79d51/forge.go#L159
https://golang.org/pkg/net/http/#ProxyFromEnvironment

I'll update the readme.

**Comment by rogerlz** [comment]
thank you. :)
